image: node:10.16.3-jessie

stages:
  - frontend
  - backend
  - deploy

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/
    - /root/.cache/Cypress

Build & CI checks frontend:
  stage: frontend
  script:
    - cd frontend
    - npm i
    - npm run lint
    - npm run build
    - cd ..

Build & CI checks backend:
  stage: backend
  script:
    - cd backend
    - npm ci
    - npm run ci:lint
    - npm run ci:prettier
    - npm run build
    - cd ..

Deploy to AWS EC2:
  stage: deploy
  script:
    - pm2 kill
    - pm2 start
  only:
    - master
