version: '3.3'

services:
  mysql:
    image: mysql:8
    restart: always

    # mysql 8 uses the new 'caching_sha2_password' auth plugin by default
    # our database driver - mysql2 - doesn't support 'caching_sha2_password'
    # so we roll back to the good old 'mysql_native_password' auth plugin
    # like so:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass123'
      MYSQL_DATABASE: 'parker'
    ports:
      - 3306:3306
    logging:
      driver: json-file
    volumes:
      - parker-mysql-db:/var/lib/mysql

  app:
    image: docker-registry.aplaline.com/parker-app
    depends_on:
      - mysql
    links:
      - mysql
    logging:
      driver: json-file
    ports:
      - 3000:3000

volumes:
  parker-mysql-db:
